/** Curated electronics parts catalog for Facksten seed (~100–120 SKUs). */

export type CategorySeed = {
  slug: string;
  name: string;
  intro: string;
  icon?: string;
  sortOrder: number;
  isPassive?: boolean;
  children?: Omit<CategorySeed, "children">[];
};

export type ProductSeed = {
  slug: string;
  title: string;
  price: number;
  compareAtPrice?: number;
  brand?: string;
  sku: string;
  mpn?: string;
  packQty?: number;
  categorySlug: string;
  stock: number;
  inStock?: boolean;
  badge?: string | null;
  isNew?: boolean;
  isPopular?: boolean;
  isFeatured?: boolean;
  image?: string;
  description: string;
  specs?: Record<string, string>;
  type?: "HARDWARE" | "DIGITAL";
  icon?: string;
  fileLabel?: string;
  fileSize?: string;
  files?: { name: string; url: string }[];
  seller?: "partner" | "partner2" | null;
};

export const CATEGORY_TREE: CategorySeed[] = [
  {
    slug: "passives",
    name: "قطعات پایه",
    intro: "مقاومت، خازن، دیود، ترانزیستور و قطعات پسیو برای مدارهای الکترونیکی.",
    icon: "memory",
    sortOrder: 10,
    children: [
      {
        slug: "resistors",
        name: "مقاومت",
        intro: "مقاومت‌های کربنی و SMD در بسته‌های استاندارد سری E12 برای نمونه‌سازی و تولید.",
        icon: "tune",
        sortOrder: 11,
        isPassive: true,
      },
      {
        slug: "capacitors",
        name: "خازن",
        intro: "خازن الکترولیتی و سرامیکی با ولتاژ و ظرفیت‌های پرکاربرد آزمایشگاهی.",
        icon: "battery_charging_full",
        sortOrder: 12,
        isPassive: true,
      },
      {
        slug: "diodes",
        name: "دیود",
        intro: "دیود یکسوساز، شاتکی و زنر برای حفاظت و یکسوسازی.",
        icon: "bolt",
        sortOrder: 13,
        isPassive: true,
      },
      {
        slug: "transistors",
        name: "ترانزیستور",
        intro: "ترانزیستورهای NPN/PNP و ماسفت برای سوییچینگ و تقویت.",
        icon: "developer_board",
        sortOrder: 14,
        isPassive: true,
      },
      {
        slug: "ics-regulators",
        name: "آی‌سی و رگولاتور",
        intro: "رگولاتورهای خطی، آپ‌امپ و آی‌سی‌های عمومی پکیج DIP/TO-220.",
        icon: "memory",
        sortOrder: 15,
        isPassive: true,
      },
    ],
  },
  {
    slug: "dev-boards",
    name: "برد و توسعه",
    intro: "بردهای آردوینو، ESP، STM و شیلدهای توسعه برای نمونه‌سازی سریع.",
    icon: "developer_board",
    sortOrder: 20,
    children: [
      {
        slug: "arduino",
        name: "آردوینو",
        intro: "بردهای خانواده Arduino برای آموزش، رباتیک و نمونه‌سازی.",
        icon: "memory",
        sortOrder: 21,
      },
      {
        slug: "esp-stm",
        name: "ESP و STM",
        intro: "ماژول‌ها و بردهای ESP32/ESP8266 و STM32 برای IoT و کنترل صنعتی سبک.",
        icon: "settings_ethernet",
        sortOrder: 22,
      },
      {
        slug: "sbc",
        name: "مینی‌کامپیوتر",
        intro: "بردهای تک‌برد مانند Raspberry Pi برای سرور سبک و هوم‌لب.",
        icon: "developer_board",
        sortOrder: 23,
      },
    ],
  },
  {
    slug: "sensors-modules",
    name: "سنسور و ماژول",
    intro: "سنسورهای محیطی، حرکتی و ماژول‌های رابط برای پروژه‌های هوشمند.",
    icon: "sensors",
    sortOrder: 30,
    children: [
      {
        slug: "sensors-env",
        name: "دما و محیط",
        intro: "سنسور دما، رطوبت، فشار و گاز برای مانیتورینگ محیطی.",
        icon: "sensors",
        sortOrder: 31,
      },
      {
        slug: "sensors-motion",
        name: "حرکت و فاصله",
        intro: "سنسور فاصله فراصوت، PIR و IMU برای رباتیک و حضور.",
        icon: "sensors",
        sortOrder: 32,
      },
      {
        slug: "modules-display",
        name: "نمایشگر",
        intro: "OLED، LCD و ماژول‌های نمایش برای رابط کاربری سخت‌افزاری.",
        icon: "developer_board",
        sortOrder: 33,
      },
      {
        slug: "modules-actuators",
        name: "درایور و عملگر",
        intro: "درایور موتور، رله، سروو و ماژول‌های قدرت سبک.",
        icon: "bolt",
        sortOrder: 34,
      },
    ],
  },
  {
    slug: "power",
    name: "تغذیه و باتری",
    intro: "ماژول‌های DC-DC، آداپتور، رگولاتور و لوازم شارژ باتری.",
    icon: "battery_charging_full",
    sortOrder: 40,
    children: [
      {
        slug: "power-modules",
        name: "ماژول تغذیه",
        intro: "باک، بوست و رگولاتورهای ماژولی برای تنظیم ولتاژ.",
        icon: "battery_charging_full",
        sortOrder: 41,
      },
      {
        slug: "adapters",
        name: "آداپتور",
        intro: "آداپتورهای دیواری با ولتاژ و جریان استاندارد آزمایشگاهی.",
        icon: "bolt",
        sortOrder: 42,
      },
      {
        slug: "batteries",
        name: "باتری و شارژ",
        intro: "سلول ۱۸۶۵۰، BMS و ماژول شارژ لییتیوم.",
        icon: "battery_charging_full",
        sortOrder: 43,
      },
    ],
  },
  {
    slug: "connectors",
    name: "کانکتور و سیم",
    intro: "هدر، ترمینال، جامپر و کانکتورهای پرکاربرد بردبورد و PCB.",
    icon: "settings_ethernet",
    sortOrder: 50,
    children: [
      {
        slug: "headers",
        name: "هدر و پین",
        intro: "هدر نری/مادگی و بریک‌اوت برای نمونه‌سازی.",
        icon: "settings_ethernet",
        sortOrder: 51,
      },
      {
        slug: "cables",
        name: "سیم و جامپر",
        intro: "کابل دپونت و سیم‌های اتصال بردبورد.",
        icon: "settings_ethernet",
        sortOrder: 52,
      },
      {
        slug: "terminals",
        name: "ترمینال",
        intro: "ترمینال پیچی و کانکتور تغذیه روی PCB.",
        icon: "settings_ethernet",
        sortOrder: 53,
      },
    ],
  },
  {
    slug: "tools",
    name: "ابزار و اندازه‌گیری",
    intro: "ابزار لحیم‌کاری، بردبورد و تجهیزات اندازه‌گیری برای کارگاه الکترونیک.",
    icon: "build",
    sortOrder: 60,
    children: [
      {
        slug: "prototyping",
        name: "نمونه‌سازی",
        intro: "بردبورد، پروتوبورد و لوازم مونتاژ موقت.",
        icon: "developer_board",
        sortOrder: 61,
      },
      {
        slug: "soldering",
        name: "لحیم‌کاری",
        intro: "هویه، سیم لحیم و ابزار ESD برای مونتاژ.",
        icon: "build",
        sortOrder: 62,
      },
      {
        slug: "measurement",
        name: "اندازه‌گیری",
        intro: "مولتی‌متر، آنالایزر منطقی و ابزار دیباگ.",
        icon: "build",
        sortOrder: 63,
      },
    ],
  },
  {
    slug: "digital",
    name: "نرم‌افزار و لایسنس",
    intro: "سورس‌کد، طراحی PCB و قالب‌های نرم‌افزاری قابل دانلود.",
    icon: "folder_zip",
    sortOrder: 70,
    children: [
      {
        slug: "source-code",
        name: "سورس‌کد پروژه",
        intro: "پروژه‌های آماده آردوینو، ESP و کنترلر.",
        icon: "folder_zip",
        sortOrder: 71,
      },
      {
        slug: "pcb-design",
        name: "طراحی PCB",
        intro: "فایل‌های طراحی مدار چاپی و استارتر پروژه‌ها.",
        icon: "schema",
        sortOrder: 72,
      },
      {
        slug: "ui-templates",
        name: "قالب و داشبورد",
        intro: "قالب‌های رابط کاربری و داشبورد IoT.",
        icon: "folder_zip",
        sortOrder: 73,
      },
    ],
  },
];

const IMG = {
  arduino: "/images/products/shop-dev-board.jpg",
  nano: "/images/products/arduino-nano.jpg",
  pi: "/images/products/shop-pi.jpg",
  esp: "/images/products/shop-esp32.jpg",
  stm: "/images/products/stm32-bluepill.jpg",
  sensor: "/images/products/shop-sensor.jpg",
  sensor2: "/images/products/sensor-module.jpg",
  hcsr: "/images/products/hc-sr04.jpg",
  chip: "/images/products/chip-macro.jpg",
  board: "/images/products/dev-board-dark.jpg",
  bread: "/images/products/breadboard.jpg",
  led: "/images/products/led-circuit.jpg",
  lifestyle: "/images/products/arduino-uno-lifestyle.jpg",
  laptop: "/images/products/laptop-desk.jpg",
  /** Discrete passives — never reuse the CPU die macro */
  resistor: "/images/products/led-circuit.jpg",
  capacitor: "/images/products/breadboard.jpg",
  diode: "/images/products/sensor-module.jpg",
  transistor: "/images/products/stm32-bluepill.jpg",
};

function resistor(
  ohm: string,
  skuCode: string,
  price: number,
  opts?: Partial<ProductSeed>,
): ProductSeed {
  return {
    ...opts,
    slug: `resistor-${skuCode.toLowerCase()}`,
    title: `مقاومت ${ohm} اهم ۱/۴ وات ۵٪ (بسته ۵۰ تایی)`,
    price,
    brand: "Yageo",
    sku: `RES-${skuCode}`,
    mpn: `CFR-25JB-${ohm}`,
    packQty: 50,
    categorySlug: "resistors",
    stock: 400,
    image: IMG.resistor,
    description: `مقاومت کربنی ${ohm} اهم، توان ۱/۴ وات، تلرانس ۵٪، بسته ۵۰ عددی مناسب نمونه‌سازی و تعمیر.`,
    specs: {
      مقدار: `${ohm} Ω`,
      توان: "1/4 W",
      تلرانس: "±5%",
      پکیج: "Axial",
      تعداد_بسته: "50",
    },
  };
}

/** Build ~110 curated hardware + digital products */
export function buildProductSeeds(): ProductSeed[] {
  const resistors: ProductSeed[] = [
    resistor("10", "10R", 18000, { isPopular: true }),
    resistor("22", "22R", 18000),
    resistor("47", "47R", 18000),
    resistor("100", "100R", 18500, { isPopular: true, badge: "پرفروش" }),
    resistor("150", "150R", 18500),
    resistor("220", "220R", 18500, { isPopular: true }),
    resistor("330", "330R", 18500),
    resistor("470", "470R", 19000),
    resistor("1K", "1K", 19000, { isPopular: true, badge: "پرفروش" }),
    resistor("2.2K", "2K2", 19000),
    resistor("4.7K", "4K7", 19500),
    resistor("10K", "10K", 19500, { isPopular: true, badge: "پرفروش" }),
    resistor("22K", "22K", 19500),
    resistor("47K", "47K", 20000),
    resistor("100K", "100K", 20000),
    resistor("220K", "220K", 20500),
    resistor("1M", "1M", 21000),
    {
      slug: "resistor-kit-e12-50",
      title: "کیت مقاومت E12 رنج پرکاربرد ۰٫۲۵ وات (بسته ۵۰ مقدار)",
      price: 750000,
      compareAtPrice: 890000,
      brand: "Facksten",
      sku: "RES-KIT-E12",
      packQty: 1,
      categorySlug: "resistors",
      stock: 45,
      isFeatured: true,
      isNew: true,
      badge: "پیشنهادی",
      image: IMG.resistor,
      description: "کیت کامل مقاومت‌های سری E12 برای میز کار؛ هر مقدار در بسته‌بندی جدا.",
      specs: { سری: "E12", توان: "0.25 W", نوع: "کربنی", کاربرد: "آموزش و نمونه‌سازی" },
    },
  ];

  const capacitors: ProductSeed[] = [
    {
      slug: "cap-elec-100uf-16v",
      title: "خازن الکترولیتی ۱۰۰ میکروفاراد ۱۶ ولت",
      price: 4500,
      brand: "Rubycon",
      sku: "CAP-100U-16",
      mpn: "100uF/16V",
      packQty: 10,
      categorySlug: "capacitors",
      stock: 500,
      isPopular: true,
      image: IMG.capacitor,
      description: "خازن الکترولیتی آلومینیومی ۱۰۰µF / ۱۶V، مناسب فیلتر تغذیه و دی‌کوپلینگ.",
      specs: { ظرفیت: "100 µF", ولتاژ: "16 V", نوع: "الکترولیتی", تعداد_بسته: "10" },
    },
    {
      slug: "cap-elec-220uf-25v",
      title: "خازن الکترولیتی ۲۲۰ میکروفاراد ۲۵ ولت",
      price: 6200,
      brand: "Nichicon",
      sku: "CAP-220U-25",
      packQty: 10,
      categorySlug: "capacitors",
      stock: 420,
      image: IMG.capacitor,
      description: "خازن الکترولیتی ۲۲۰µF / ۲۵V برای منبع تغذیه و مدارهای قدرت سبک.",
      specs: { ظرفیت: "220 µF", ولتاژ: "25 V", نوع: "الکترولیتی" },
    },
    {
      slug: "cap-elec-470uf-25v",
      title: "خازن الکترولیتی ۴۷۰ میکروفاراد ۲۵ ولت",
      price: 8900,
      brand: "Samwha",
      sku: "CAP-470U-25",
      packQty: 5,
      categorySlug: "capacitors",
      stock: 300,
      image: IMG.capacitor,
      description: "خازن الکترولیتی ۴۷۰µF / ۲۵V برای فیلتر خروجی رگولاتور.",
      specs: { ظرفیت: "470 µF", ولتاژ: "25 V" },
    },
    {
      slug: "cap-elec-1000uf-16v",
      title: "خازن الکترولیتی ۱۰۰۰ میکروفاراد ۱۶ ولت",
      price: 12000,
      compareAtPrice: 14500,
      brand: "LELON",
      sku: "CAP-1000U-16",
      packQty: 5,
      categorySlug: "capacitors",
      stock: 260,
      badge: "تخفیف",
      image: IMG.capacitor,
      description: "خازن الکترولیتی ۱۰۰۰µF / ۱۶V سری RXK.",
      specs: { ظرفیت: "1000 µF", ولتاژ: "16 V" },
    },
    {
      slug: "cap-cer-100nf-50v",
      title: "خازن سرامیکی ۱۰۰ نانوفاراد ۵۰ ولت (۱۰۴)",
      price: 1800,
      brand: "Generic",
      sku: "CAP-100N-50",
      packQty: 50,
      categorySlug: "capacitors",
      stock: 800,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.capacitor,
      description: "خازن سرامیکی دیسکی ۱۰۰nF برای دی‌کوپلینگ آی‌سی.",
      specs: { ظرفیت: "100 nF", ولتاژ: "50 V", کد: "104" },
    },
    {
      slug: "cap-cer-22pf",
      title: "خازن سرامیکی ۲۲ پیکوفاراد",
      price: 1500,
      brand: "Generic",
      sku: "CAP-22P",
      packQty: 50,
      categorySlug: "capacitors",
      stock: 600,
      image: IMG.capacitor,
      description: "خازن سرامیکی ۲۲pF مناسب کریستال و مدارهای RF سبک.",
      specs: { ظرفیت: "22 pF", نوع: "سرامیکی" },
    },
    {
      slug: "cap-cer-10uf-0805",
      title: "خازن SMD 10uF سایز ۰۸۰۵",
      price: 3200,
      brand: "Murata",
      sku: "CAP-10U-0805",
      packQty: 20,
      categorySlug: "capacitors",
      stock: 350,
      isNew: true,
      image: IMG.capacitor,
      description: "خازن سرامیکی SMD ۱۰µF پکیج ۰۸۰۵.",
      specs: { ظرفیت: "10 µF", پکیج: "0805", نوع: "MLCC" },
    },
  ];

  const diodes: ProductSeed[] = [
    {
      slug: "diode-1n4007",
      title: "دیود یکسوساز 1N4007 (بسته ۵۰ تایی)",
      price: 35000,
      brand: "ON Semi",
      sku: "DIO-1N4007-50",
      mpn: "1N4007",
      packQty: 50,
      categorySlug: "diodes",
      stock: 900,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.diode,
      description: "دیود 1N4007 با ولتاژ معکوس ۱۰۰۰ ولت و جریان ۱ آمپر.",
      specs: { مدل: "1N4007", ولتاژ: "1000 V", جریان: "1 A", تعداد_بسته: "50" },
    },
    {
      slug: "diode-1n4148",
      title: "دیود سوییچینگ 1N4148 (بسته ۱۰۰ تایی)",
      price: 28000,
      brand: "NXP",
      sku: "DIO-1N4148-100",
      mpn: "1N4148",
      packQty: 100,
      categorySlug: "diodes",
      stock: 700,
      image: IMG.diode,
      description: "دیود سریع 1N4148 برای سیگنال و حفاظت.",
      specs: { مدل: "1N4148", نوع: "سوییچینگ", تعداد_بسته: "100" },
    },
    {
      slug: "diode-1n5819",
      title: "دیود شاتکی 1N5819",
      price: 4500,
      brand: "Vishay",
      sku: "DIO-1N5819",
      mpn: "1N5819",
      packQty: 10,
      categorySlug: "diodes",
      stock: 400,
      image: IMG.diode,
      description: "دیود شاتکی ۱ آمپر ۴۰ ولت با افت ولتاژ پایین.",
      specs: { مدل: "1N5819", ولتاژ: "40 V", جریان: "1 A" },
    },
    {
      slug: "diode-zener-5v1",
      title: "دیود زنر ۵٫۱ ولت 1N4733A",
      price: 3200,
      brand: "ON Semi",
      sku: "DIO-ZEN-5V1",
      packQty: 20,
      categorySlug: "diodes",
      stock: 450,
      image: IMG.diode,
      description: "دیود زنر ۵٫۱ ولت برای تثبیت ولتاژ مرجع.",
      specs: { ولتاژ_زنر: "5.1 V", توان: "1 W" },
    },
    {
      slug: "bridge-mb10s",
      title: "پل دیود مربعی MB10S",
      price: 8500,
      brand: "Generic",
      sku: "DIO-MB10S",
      packQty: 5,
      categorySlug: "diodes",
      stock: 220,
      isNew: true,
      image: IMG.diode,
      description: "پل یکسوساز ۰٫۵ آمپر ۱۰۰۰ ولت پکیج مربعی.",
      specs: { مدل: "MB10S", ولتاژ: "1000 V", جریان: "0.5 A" },
    },
  ];

  const transistors: ProductSeed[] = [
    {
      slug: "tr-bc547",
      title: "ترانزیستور BC547 نوع NPN (بسته ۱۰ تایی)",
      price: 12000,
      brand: "NXP",
      sku: "TR-BC547-10",
      mpn: "BC547",
      packQty: 10,
      categorySlug: "transistors",
      stock: 600,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.transistor,
      description: "ترانزیستور NPN عمومی BC547 پکیج TO-92.",
      specs: { مدل: "BC547", نوع: "NPN", پکیج: "TO-92" },
    },
    {
      slug: "tr-bc557",
      title: "ترانزیستور BC557 نوع PNP (بسته ۱۰ تایی)",
      price: 12500,
      brand: "NXP",
      sku: "TR-BC557-10",
      mpn: "BC557",
      packQty: 10,
      categorySlug: "transistors",
      stock: 550,
      image: IMG.transistor,
      description: "ترانزیستور PNP مکمل BC557.",
      specs: { مدل: "BC557", نوع: "PNP", پکیج: "TO-92" },
    },
    {
      slug: "tr-2n2222",
      title: "ترانزیستور 2N2222A",
      price: 5500,
      brand: "ST",
      sku: "TR-2N2222",
      mpn: "2N2222A",
      packQty: 10,
      categorySlug: "transistors",
      stock: 480,
      image: IMG.transistor,
      description: "ترانزیستور سوییچینگ NPN محبوب 2N2222A.",
      specs: { مدل: "2N2222A", نوع: "NPN" },
    },
    {
      slug: "tr-irfz44n",
      title: "ماسفت قدرت IRFZ44N",
      price: 28000,
      brand: "Infineon",
      sku: "TR-IRFZ44N",
      mpn: "IRFZ44N",
      packQty: 1,
      categorySlug: "transistors",
      stock: 180,
      isPopular: true,
      image: IMG.chip,
      description: "ماسفت N-Channel ۵۵ ولت ۴۹ آمپر برای درایو موتور و LED.",
      specs: { مدل: "IRFZ44N", ولتاژ: "55 V", جریان: "49 A", پکیج: "TO-220" },
    },
    {
      slug: "tr-ao3401",
      title: "ماسفت P کانال AO3401",
      price: 6500,
      brand: "Alpha & Omega",
      sku: "TR-AO3401",
      mpn: "AO3401",
      packQty: 10,
      categorySlug: "transistors",
      stock: 320,
      isNew: true,
      image: IMG.chip,
      description: "ماسفت P-Channel ۳۰ ولت مناسب سوییچینگ سمت بالا.",
      specs: { مدل: "AO3401", نوع: "P-MOSFET", ولتاژ: "30 V" },
    },
  ];

  const ics: ProductSeed[] = [
    {
      slug: "ic-7805",
      title: "رگولاتور ۵ ولت L7805CV پکیج TO-220",
      price: 18000,
      brand: "ST",
      sku: "IC-7805",
      mpn: "L7805CV",
      categorySlug: "ics-regulators",
      stock: 400,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.chip,
      description: "رگولاتور خطی مثبت ۵ ولت با جریان تا ۱٫۵ آمپر.",
      specs: { مدل: "L7805CV", خروجی: "5 V", پکیج: "TO-220" },
    },
    {
      slug: "ic-7812",
      title: "رگولاتور ۱۲ ولت L7812CV",
      price: 19500,
      brand: "ST",
      sku: "IC-7812",
      mpn: "L7812CV",
      categorySlug: "ics-regulators",
      stock: 280,
      image: IMG.chip,
      description: "رگولاتور خطی ۱۲ ولت TO-220.",
      specs: { مدل: "L7812CV", خروجی: "12 V" },
    },
    {
      slug: "ic-lm317",
      title: "رگولاتور قابل تنظیم LM317",
      price: 22000,
      brand: "TI",
      sku: "IC-LM317",
      mpn: "LM317T",
      categorySlug: "ics-regulators",
      stock: 350,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.chip,
      description: "رگولاتور قابل تنظیم ۱٫۲۵ تا ۳۷ ولت.",
      specs: { مدل: "LM317", پکیج: "TO-220" },
    },
    {
      slug: "ic-ne555",
      title: "آی‌سی تایمر NE555",
      price: 8500,
      brand: "TI",
      sku: "IC-NE555",
      mpn: "NE555P",
      categorySlug: "ics-regulators",
      stock: 500,
      image: IMG.chip,
      description: "تایمر کلاسیک NE555 پکیج DIP-8.",
      specs: { مدل: "NE555", پکیج: "DIP-8" },
    },
    {
      slug: "ic-lm358",
      title: "آپ‌امپ دوگانه LM358",
      price: 9000,
      brand: "TI",
      sku: "IC-LM358",
      mpn: "LM358N",
      categorySlug: "ics-regulators",
      stock: 420,
      image: IMG.chip,
      description: "آپ‌امپ دوگانه کم‌مصرف برای سیگنال آنالوگ.",
      specs: { مدل: "LM358", پکیج: "DIP-8" },
    },
    {
      slug: "ic-atmega8",
      title: "میکروکنترلر ATMEGA8A-PU پکیج PDIP-28",
      price: 185000,
      brand: "Microchip",
      sku: "IC-ATMEGA8A",
      mpn: "ATMEGA8A-PU",
      categorySlug: "ics-regulators",
      stock: 90,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.chip,
      description: "میکروکنترلر AVR هشت‌بیتی محبوب برای پروژه‌های آموزشی.",
      specs: { مدل: "ATmega8A", فلش: "8 KB", پکیج: "PDIP-28" },
    },
    {
      slug: "ic-atmega328p",
      title: "میکروکنترلر ATMEGA328P-PU",
      price: 245000,
      brand: "Microchip",
      sku: "IC-ATMEGA328P",
      mpn: "ATMEGA328P-PU",
      categorySlug: "ics-regulators",
      stock: 120,
      isFeatured: true,
      image: IMG.chip,
      description: "قلب بسیاری از بردهای Arduino Uno؛ فلش ۳۲ کیلوبایت.",
      specs: { مدل: "ATmega328P", فلش: "32 KB", پکیج: "PDIP-28" },
    },
  ];

  const arduino: ProductSeed[] = [
    {
      slug: "arduino-uno-r3",
      title: "برد توسعه آردوینو Uno R3 اورجینال",
      price: 850000,
      brand: "Arduino",
      sku: "ARD-UNO-R3",
      mpn: "A000066",
      categorySlug: "arduino",
      stock: 40,
      isPopular: true,
      isFeatured: true,
      badge: "پرفروش",
      image: "/images/products/shop-dev-board.jpg",
      seller: "partner",
      description:
        "برد آردوینو Uno R3 با میکروکنترلر ATmega328P اورجینال. مناسب آموزش، نمونه‌سازی و پروژه‌های رباتیک.",
      specs: {
        میکروکنترلر: "ATmega328P",
        ولتاژ: "5 V",
        پین_دیجیتال: "14",
        پین_آنالوگ: "6",
        کلاک: "16 MHz",
      },
    },
    {
      slug: "arduino-uno-ch340",
      title: "برد آردوینو Uno R3 CH340 با ورودی Type-C",
      price: 420000,
      compareAtPrice: 480000,
      brand: "Compatible",
      sku: "ARD-UNO-CH340",
      categorySlug: "arduino",
      stock: 95,
      isNew: true,
      badge: "جدید",
      image: IMG.lifestyle,
      seller: "partner",
      description: "نسخه سازگار Uno با چیپ سریال CH340 و کانکتور USB Type-C.",
      specs: { چیپ_سریال: "CH340", کانکتور: "USB-C", میکروکنترلر: "ATmega328P" },
    },
    {
      slug: "arduino-nano",
      title: "برد آردوینو Nano با هدر لحیم‌شده",
      price: 320000,
      brand: "Arduino",
      sku: "ARD-NANO",
      categorySlug: "arduino",
      stock: 85,
      isPopular: true,
      badge: "پیشنهادی",
      image: IMG.nano,
      seller: "partner",
      description: "نسخه فشرده آردوینو با ATmega328P، مناسب بردبورد و پروژه‌های فضای محدود.",
      specs: { میکروکنترلر: "ATmega328P", فرم_فاکتور: "Nano", هدر: "لحیم‌شده" },
    },
    {
      slug: "arduino-mega-2560",
      title: "برد آردوینو Mega 2560 R3",
      price: 1250000,
      brand: "Compatible",
      sku: "ARD-MEGA2560",
      categorySlug: "arduino",
      stock: 35,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.arduino,
      seller: "partner2",
      description: "برد Mega با ATmega2560، ۵۴ پین دیجیتال و ۱۶ ورودی آنالوگ.",
      specs: { میکروکنترلر: "ATmega2560", پین_دیجیتال: "54", پین_آنالوگ: "16" },
    },
    {
      slug: "arduino-pro-mini",
      title: "برد آردوینو Pro Mini 5V 16MHz",
      price: 185000,
      brand: "Compatible",
      sku: "ARD-PROMINI-5V",
      categorySlug: "arduino",
      stock: 110,
      image: IMG.nano,
      description: "برد فشرده بدون USB onboard؛ نیاز به مبدل FTDI.",
      specs: { ولتاژ: "5 V", کلاک: "16 MHz" },
    },
    {
      slug: "sensor-kit-37",
      title: "پک ۳۷ عددی ماژول و سنسور آموزشی آردوینو",
      price: 890000,
      compareAtPrice: 1050000,
      brand: "Facksten",
      sku: "ARD-KIT-37",
      categorySlug: "arduino",
      stock: 55,
      isFeatured: true,
      isNew: true,
      badge: "پیشنهادی",
      image: IMG.sensor2,
      seller: "partner",
      description: "کیت کامل سنسور و ماژول آموزشی سازگار با Arduino.",
      specs: { تعداد: "37 قطعه", کاربرد: "آموزش" },
    },
  ];

  const espStm: ProductSeed[] = [
    {
      slug: "esp32-wroom",
      title: "ماژول وای‌فای و بلوتوث ESP32-WROOM-32",
      price: 240000,
      brand: "Espressif",
      sku: "ESP-WROOM-32",
      mpn: "ESP32-WROOM-32",
      categorySlug: "esp-stm",
      stock: 120,
      isNew: true,
      isPopular: true,
      badge: "جدید",
      image: IMG.esp,
      seller: "partner",
      description: "ماژول ESP32 با وای‌فای و بلوتوث BLE برای پروژه‌های IoT.",
      specs: { وای‌فای: "802.11 b/g/n", بلوتوث: "BLE", ولتاژ: "3.3 V" },
    },
    {
      slug: "esp32-devkit-c",
      title: "برد توسعه ESP32 DevKitC با Type-C",
      price: 385000,
      brand: "Espressif",
      sku: "ESP-DEVKIT-C",
      categorySlug: "esp-stm",
      stock: 70,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.esp,
      seller: "partner",
      description: "برد توسعه ۳۸ پایه ESP32 با ورودی USB Type-C.",
      specs: { پایه: "38", کانکتور: "USB-C" },
    },
    {
      slug: "esp8266-nodemcu",
      title: "برد NodeMCU ESP8266",
      price: 165000,
      brand: "Espressif",
      sku: "ESP-NODEMCU",
      categorySlug: "esp-stm",
      stock: 140,
      image: IMG.board,
      description: "برد NodeMCU مبتنی بر ESP8266 برای پروژه‌های وای‌فای اقتصادی.",
      specs: { چیپ: "ESP8266", وای‌فای: "بله" },
    },
    {
      slug: "stm32-bluepill",
      title: "برد توسعه STM32F103C8T6 Blue Pill",
      price: 185000,
      brand: "STMicro",
      sku: "STM-BLUEPILL",
      mpn: "STM32F103C8T6",
      categorySlug: "esp-stm",
      stock: 60,
      image: IMG.stm,
      seller: "partner2",
      description: "برد Blue Pill مبتنی بر Cortex-M3 با ۷۲ مگاهرتز.",
      specs: { هسته: "Cortex-M3", فرکانس: "72 MHz", فلش: "64 KB" },
    },
    {
      slug: "stm32-nucleo",
      title: "برد توسعه STM32 Nucleo-F401RE",
      price: 1450000,
      brand: "STMicro",
      sku: "STM-NUCLEO-F401",
      categorySlug: "esp-stm",
      stock: 18,
      isNew: true,
      badge: "جدید",
      image: IMG.stm,
      seller: "partner2",
      description: "برد رسمی Nucleo با دیباگر ST-LINK داخلی.",
      specs: { مدل: "NUCLEO-F401RE", دیباگر: "ST-LINK" },
    },
  ];

  const sbc: ProductSeed[] = [
    {
      slug: "raspberry-pi-4-8gb",
      title: "رسپبری پای 4 مدل B ظرفیت 8 گیگابایت",
      price: 4200000,
      brand: "Raspberry Pi",
      sku: "RPI4-8GB",
      mpn: "RPI4-MODBP-8GB",
      categorySlug: "sbc",
      stock: 0,
      inStock: false,
      image: IMG.pi,
      seller: "partner",
      description: "کامپیوتر تک‌برد Raspberry Pi 4 با ۸ گیگابایت رم.",
      specs: { رم: "8 GB", HDMI: "دوگانه", USB: "USB 3.0" },
    },
    {
      slug: "raspberry-pi-zero-2w",
      title: "برد Raspberry Pi Zero 2 W",
      price: 1850000,
      brand: "Raspberry Pi",
      sku: "RPI-ZERO2W",
      categorySlug: "sbc",
      stock: 22,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.pi,
      seller: "partner",
      description: "مینی‌کامپیوتر فشرده با وای‌فای و بلوتوث داخلی.",
      specs: { وای‌فای: "بله", بلوتوث: "بله", فرم: "Zero" },
    },
  ];

  const sensors: ProductSeed[] = [
    {
      slug: "hc-sr04",
      title: "ماژول سنسور فاصله‌سنج التراسونیک HC-SR04",
      price: 45000,
      brand: "Generic",
      sku: "SEN-HCSR04",
      categorySlug: "sensors-modules",
      stock: 200,
      image: IMG.hcsr,
      description: "سنسور التراسونیک با دقت اندازه‌گیری ۲ تا ۴۰۰ سانتی‌متر.",
      specs: { برد: "2–400 cm", ولتاژ: "5 V" },
    },
    {
      slug: "dht22",
      title: "سنسور دما و رطوبت دیجیتال DHT22",
      price: 78000,
      brand: "Aosong",
      sku: "SEN-DHT22",
      mpn: "AM2302",
      categorySlug: "sensors-modules",
      stock: 95,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.sensor,
      seller: "partner",
      description: "سنسور دقیق دما و رطوبت نسبی با خروجی دیجیتال.",
      specs: { دما: "−40 تا 80°C", رطوبت: "0–100%" },
    },
    {
      slug: "dht11",
      title: "سنسور دما و رطوبت DHT11",
      price: 32000,
      brand: "Aosong",
      sku: "SEN-DHT11",
      categorySlug: "sensors-modules",
      stock: 180,
      image: IMG.sensor,
      description: "سنسور اقتصادی دما و رطوبت برای پروژه‌های آموزشی.",
      specs: { دقت_دما: "±2°C" },
    },
    {
      slug: "mpu6050",
      title: "ماژول IMU شتاب‌سنج و ژیروسکوپ MPU6050",
      price: 125000,
      brand: "InvenSense",
      sku: "SEN-MPU6050",
      mpn: "MPU-6050",
      categorySlug: "sensors-modules",
      stock: 55,
      isNew: true,
      badge: "جدید",
      image: IMG.sensor2,
      seller: "partner",
      description: "سنسور ۶ محوره با رابط I2C.",
      specs: { محور: "6", رابط: "I2C" },
    },
    {
      slug: "oled-128x64",
      title: "نمایشگر OLED 0.96 اینچ I2C سفید",
      price: 95000,
      brand: "Generic",
      sku: "MOD-OLED096",
      categorySlug: "sensors-modules",
      stock: 150,
      image: IMG.sensor,
      description: "نمایشگر OLED ۱۲۸×۶۴ با رابط I2C.",
      specs: { رزولوشن: "128×64", رابط: "I2C" },
    },
    {
      slug: "lcd-1602",
      title: "نمایشگر LCD کاراکتری ۲×۱۶ بک‌لایت آبی",
      price: 85000,
      brand: "Generic",
      sku: "MOD-LCD1602",
      categorySlug: "sensors-modules",
      stock: 130,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.led,
      description: "ال‌سی‌دی کاراکتری ۱۶×۲ با بک‌لایت.",
      specs: { سطر: "2", کاراکتر: "16" },
    },
    {
      slug: "l298n-driver",
      title: "درایور موتور دو کاناله L298N",
      price: 110000,
      brand: "Generic",
      sku: "MOD-L298N",
      categorySlug: "sensors-modules",
      stock: 70,
      image: IMG.board,
      seller: "partner2",
      description: "ماژول درایور موتور برای دو موتور DC یا یک استپر.",
      specs: { کانال: "2", ولتاژ_منطق: "5 V" },
    },
    {
      slug: "relay-5v-1ch",
      title: "ماژول رله ۵ ولت تک کاناله",
      price: 35000,
      brand: "Generic",
      sku: "MOD-RELAY-1CH",
      categorySlug: "sensors-modules",
      stock: 210,
      image: IMG.board,
      description: "رله ۵ ولت با اپتوکوپلر برای کنترل بار AC/DC.",
      specs: { کانال: "1", ولتاژ_کویل: "5 V" },
    },
    {
      slug: "rfid-rc522",
      title: "ماژول RFID RC522 به‌همراه تگ و کارت",
      price: 95000,
      brand: "NXP",
      sku: "MOD-RC522",
      categorySlug: "sensors-modules",
      stock: 85,
      isFeatured: true,
      image: IMG.sensor2,
      description: "ماژول RFID ۱۳٫۵۶ مگاهرتز با یک کارت و یک تگ.",
      specs: { فرکانس: "13.56 MHz", رابط: "SPI" },
    },
    {
      slug: "pir-hc-sr501",
      title: "سنسور حرکت PIR HC-SR501",
      price: 42000,
      brand: "Generic",
      sku: "SEN-PIR501",
      categorySlug: "sensors-modules",
      stock: 160,
      image: IMG.sensor,
      description: "سنسور مادون قرمز تشخیص حرکت برای امنیتی و اتوماسیون.",
      specs: { برد: "تا 7 m", ولتاژ: "5–20 V" },
    },
    {
      slug: "mq2-gas",
      title: "سنسور گاز MQ-2",
      price: 48000,
      brand: "Winsen",
      sku: "SEN-MQ2",
      categorySlug: "sensors-modules",
      stock: 100,
      image: IMG.sensor2,
      description: "سنسور گازهای قابل اشتعال و دود.",
      specs: { مدل: "MQ-2", خروجی: "آنالوگ/دیجیتال" },
    },
    {
      slug: "bmp280",
      title: "ماژول فشار و دما BMP280",
      price: 72000,
      brand: "Bosch",
      sku: "SEN-BMP280",
      mpn: "BMP280",
      categorySlug: "sensors-modules",
      stock: 75,
      isNew: true,
      image: IMG.sensor,
      description: "سنسور فشار بارومتریک و دما با I2C/SPI.",
      specs: { رابط: "I2C/SPI", کاربرد: "ارتفاع‌سنج" },
    },
  ];

  const power: ProductSeed[] = [
    {
      slug: "mod-lm2596",
      title: "ماژول کاهنده DC-DC LM2596",
      price: 65000,
      brand: "Generic",
      sku: "PWR-LM2596",
      categorySlug: "power",
      stock: 190,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.board,
      description: "مبدل کاهنده قابل تنظیم تا ۳ آمپر.",
      specs: { نوع: "Buck", جریان: "3 A" },
    },
    {
      slug: "mod-mt3608",
      title: "ماژول افزاینده MT3608",
      price: 38000,
      brand: "Generic",
      sku: "PWR-MT3608",
      categorySlug: "power",
      stock: 220,
      image: IMG.board,
      description: "بوستر ۲ آمپر برای بالا بردن ولتاژ باتری.",
      specs: { نوع: "Boost", جریان: "2 A" },
    },
    {
      slug: "adapter-12v-1a",
      title: "آداپتور ۱۲ ولت ۱ آمپر دیواری",
      price: 145000,
      brand: "Facksten",
      sku: "PWR-ADP-12V1A",
      categorySlug: "power",
      stock: 80,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.board,
      description: "آداپتور دیواری ۱۲V-1A مناسب دوربین و رگولاتور.",
      specs: { خروجی: "12 V", جریان: "1 A" },
    },
    {
      slug: "adapter-5v-2a",
      title: "آداپتور ۵ ولت ۲ آمپر USB",
      price: 98000,
      brand: "Facksten",
      sku: "PWR-ADP-5V2A",
      categorySlug: "power",
      stock: 120,
      image: IMG.board,
      description: "تغذیه ۵ ولت ۲ آمپر با خروجی USB.",
      specs: { خروجی: "5 V", جریان: "2 A" },
    },
    {
      slug: "tp4056-module",
      title: "ماژول شارژر باتری لیتیوم TP4056 با حفاظت",
      price: 28000,
      brand: "Generic",
      sku: "PWR-TP4056",
      categorySlug: "power",
      stock: 300,
      isNew: true,
      badge: "جدید",
      image: IMG.led,
      description: "شارژر تک‌سل لیتیوم با Type-C و حفاظت باتری.",
      specs: { چیپ: "TP4056", سلول: "1S" },
    },
    {
      slug: "battery-18650",
      title: "باتری لیتیوم یون ۱۸۶۵۰ ظرفیت ۲۲۰۰ میلی‌آمپرساعت",
      price: 95000,
      brand: "Ultra Power",
      sku: "PWR-18650-2200",
      categorySlug: "power",
      stock: 150,
      image: IMG.board,
      description: "سل ۱۸۶۵۰ سرتخت ۲۲۰۰mAh.",
      specs: { ولتاژ: "3.7 V", ظرفیت: "2200 mAh" },
    },
  ];

  const connectors: ProductSeed[] = [
    {
      slug: "header-male-40",
      title: "پین هدر نری ۴۰ پین ۲٫۵۴ میلی‌متر",
      price: 12000,
      brand: "Generic",
      sku: "CON-HDR-M40",
      packQty: 5,
      categorySlug: "connectors",
      stock: 400,
      image: IMG.bread,
      description: "پین هدر نری قابل شکستن برای بردهای توسعه.",
      specs: { گام: "2.54 mm", تعداد: "40" },
    },
    {
      slug: "header-female-40",
      title: "پین هدر مادگی ۴۰ پین",
      price: 18000,
      brand: "Generic",
      sku: "CON-HDR-F40",
      packQty: 5,
      categorySlug: "connectors",
      stock: 350,
      image: IMG.bread,
      description: "هدر مادگی برای شیلد و بردبورد.",
      specs: { گام: "2.54 mm" },
    },
    {
      slug: "dupont-jumper-65",
      title: "بسته ۶۵ عددی کابل جامپر نری به نری",
      price: 45000,
      brand: "Generic",
      sku: "CON-JMP-65",
      categorySlug: "connectors",
      stock: 280,
      isPopular: true,
      image: IMG.bread,
      description: "کابل جامپر رنگی برای اتصال سریع.",
      specs: { تعداد: "65", نوع: "نری-نری" },
    },
    {
      slug: "terminal-kf301-2p",
      title: "ترمینال پیچی ۲ پین KF301",
      price: 8500,
      brand: "Generic",
      sku: "CON-KF301-2",
      packQty: 10,
      categorySlug: "connectors",
      stock: 500,
      image: IMG.bread,
      description: "ترمینال پیچی سبز ۲ پایه برای منبع تغذیه.",
      specs: { پایه: "2", مدل: "KF301" },
    },
    {
      slug: "usb-typec-breakout",
      title: "برد تبدیل USB Type-C به پین هدر",
      price: 35000,
      brand: "Generic",
      sku: "CON-USBC-BO",
      categorySlug: "connectors",
      stock: 90,
      isNew: true,
      image: IMG.board,
      description: "برک‌اوت Type-C برای تغذیه و داده.",
      specs: { کانکتور: "USB-C" },
    },
  ];

  const tools: ProductSeed[] = [
    {
      slug: "breadboard-830",
      title: "بردبورد ۸۳۰ نقطه همراه با کابل جامپر",
      price: 65000,
      brand: "Generic",
      sku: "TOL-BB830",
      categorySlug: "tools",
      stock: 300,
      image: IMG.bread,
      description: "بردبورد استاندارد ۸۳۰ نقطه همراه بسته جامپر.",
      specs: { نقاط: "830", همراه: "جامپر" },
    },
    {
      slug: "logic-analyzer-8ch",
      title: "آنالایزر منطقی ۸ کاناله USB",
      price: 690000,
      brand: "Saleae Compatible",
      sku: "TOL-LA8",
      categorySlug: "tools",
      stock: 25,
      image: IMG.esp,
      seller: "partner2",
      description: "آنالایزر منطقی برای دیباگ UART، I2C و SPI.",
      specs: { کانال: "8", رابط: "USB" },
    },
    {
      slug: "soldering-iron-60w",
      title: "هویه ۶۰ وات قابل تنظیم دما",
      price: 320000,
      brand: "Facksten Tools",
      sku: "TOL-IRON60",
      categorySlug: "tools",
      stock: 40,
      isFeatured: true,
      badge: "پیشنهادی",
      image: IMG.board,
      description: "هویه ۶۰ وات با پایه و اسفنج.",
      specs: { توان: "60 W", دما: "قابل تنظیم" },
    },
    {
      slug: "solder-wire-100g",
      title: "سیم قلع ۶۳٪ وزن ۱۰۰ گرم",
      price: 185000,
      brand: "Behinex",
      sku: "TOL-SOLDER100",
      categorySlug: "tools",
      stock: 70,
      image: IMG.led,
      description: "سیم لحیم ۶۳/۳۷ با فلاکس داخلی.",
      specs: { آلیاژ: "63/37", وزن: "100 g" },
    },
    {
      slug: "tweezers-esd",
      title: "پنس آنتی‌استاتیک سرکج",
      price: 95000,
      brand: "Welsolo",
      sku: "TOL-TWEEZ-ESD",
      categorySlug: "tools",
      stock: 60,
      isNew: true,
      image: IMG.led,
      description: "پنس ESD مناسب قطعات SMD.",
      specs: { نوع: "سرکج", ESD: "بله" },
    },
    {
      slug: "multimeter-aneng",
      title: "مولتی‌متر دیجیتال جیبی",
      price: 420000,
      brand: "ANENG",
      sku: "TOL-DMM-MINI",
      categorySlug: "tools",
      stock: 35,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.board,
      description: "مولتی‌متر دستی برای ولتاژ، جریان و مقاومت.",
      specs: { نمایش: "دیجیتال", کاربرد: "عمومی" },
    },
  ];

  const extras: ProductSeed[] = [
    {
      slug: "resistor-smd-10k-0805",
      title: "مقاومت SMD 10K اهم ۰۸۰۵ (بسته ۱۰۰ تایی)",
      price: 45000,
      brand: "Yageo",
      sku: "RES-SMD-10K-0805",
      packQty: 100,
      categorySlug: "resistors",
      stock: 250,
      isNew: true,
      image: IMG.resistor,
      description: "مقاومت SMD ۱۰ کیلو اهم تلرانس ۱٪ سایز ۰۸۰۵.",
      specs: { مقدار: "10K Ω", پکیج: "0805", تلرانس: "±1%" },
    },
    {
      slug: "cap-elec-47uf-25v",
      title: "خازن الکترولیتی ۴۷ میکروفاراد ۲۵ ولت",
      price: 3800,
      brand: "Samwha",
      sku: "CAP-47U-25",
      packQty: 20,
      categorySlug: "capacitors",
      stock: 380,
      image: IMG.capacitor,
      description: "خازن الکترولیتی ۴۷µF / ۲۵V.",
      specs: { ظرفیت: "47 µF", ولتاژ: "25 V" },
    },
    {
      slug: "led-5mm-red-pack",
      title: "ال‌ای‌دی ۵ میلی‌متری قرمز (بسته ۲۵ تایی)",
      price: 22000,
      brand: "Generic",
      sku: "LED-5MM-RED-25",
      packQty: 25,
      categorySlug: "diodes",
      stock: 400,
      image: IMG.led,
      description: "ال‌ای‌دی ۵mm قرمز استاندارد برای بردبورد.",
      specs: { رنگ: "قرمز", قطر: "5 mm" },
    },
    {
      slug: "led-5mm-rgb",
      title: "ال‌ای‌دی RGB پایه مشترک کاتد",
      price: 8500,
      brand: "Generic",
      sku: "LED-RGB-CC",
      packQty: 5,
      categorySlug: "diodes",
      stock: 200,
      image: IMG.led,
      description: "ال‌ای‌دی سه‌رنگ RGB با کاتد مشترک.",
      specs: { نوع: "RGB", کاتد: "مشترک" },
    },
    {
      slug: "crystal-16mhz",
      title: "کریستال ۱۶ مگاهرتز به‌همراه خازن بار",
      price: 12000,
      brand: "Generic",
      sku: "XTAL-16M",
      packQty: 5,
      categorySlug: "ics-regulators",
      stock: 300,
      image: IMG.capacitor,
      description: "کریستال ۱۶MHz مناسب AVR و Arduino.",
      specs: { فرکانس: "16 MHz" },
    },
    {
      slug: "arduino-leonardo",
      title: "برد آردوینو Leonardo R3",
      price: 680000,
      brand: "Compatible",
      sku: "ARD-LEONARDO",
      categorySlug: "arduino",
      stock: 28,
      image: IMG.arduino,
      seller: "partner",
      description: "برد Leonardo با ATmega32U4 و USB HID داخلی.",
      specs: { میکروکنترلر: "ATmega32U4", HID: "بله" },
    },
    {
      slug: "wemos-d1-mini",
      title: "برد WeMos D1 Mini ESP8266",
      price: 145000,
      brand: "Wemos",
      sku: "ESP-D1MINI",
      categorySlug: "esp-stm",
      stock: 95,
      isPopular: true,
      image: IMG.board,
      description: "برد فشرده ESP8266 با هدر لحیم‌شده.",
      specs: { چیپ: "ESP8266", فرم: "D1 Mini" },
    },
    {
      slug: "ssd1306-blue",
      title: "نمایشگر OLED 0.96 اینچ آبی I2C",
      price: 98000,
      brand: "Generic",
      sku: "MOD-OLED096-BL",
      categorySlug: "sensors-modules",
      stock: 110,
      image: IMG.sensor,
      description: "OLED آبی ۱۲۸×۶۴ با درایور SSD1306.",
      specs: { رنگ: "آبی", رابط: "I2C" },
    },
    {
      slug: "servo-sg90",
      title: "سروموتور میکرو SG90",
      price: 55000,
      brand: "Tower Pro",
      sku: "ACT-SG90",
      categorySlug: "sensors-modules",
      stock: 170,
      isPopular: true,
      badge: "پرفروش",
      image: IMG.board,
      description: "سروموتور ۹ گرم مناسب رباتیک آموزشی.",
      specs: { گشتاور: "1.8 kg·cm", ولتاژ: "4.8–6 V" },
    },
    {
      slug: "stepper-28byj",
      title: "استپر موتور ۲۸BYJ-۴۸ به‌همراه درایور ULN2003",
      price: 95000,
      brand: "Generic",
      sku: "ACT-28BYJ",
      categorySlug: "sensors-modules",
      stock: 80,
      image: IMG.board,
      description: "موتور پله‌ای ۵ ولت با برد درایور.",
      specs: { مدل: "28BYJ-48", ولتاژ: "5 V" },
    },
    {
      slug: "bms-1s-10a",
      title: "ماژول BMS تک‌سل ۱۰ آمپر",
      price: 42000,
      brand: "Generic",
      sku: "PWR-BMS-1S10A",
      categorySlug: "power",
      stock: 140,
      image: IMG.led,
      description: "برد حفاظت شارژ/دشارژ باتری لیتیوم ۱S.",
      specs: { سلول: "1S", جریان: "10 A" },
    },
    {
      slug: "protoboard-7x9",
      title: "فیبر سوراخ‌دار ۷×۹ سانتی‌متر",
      price: 28000,
      brand: "Generic",
      sku: "TOL-PROTO-7X9",
      packQty: 2,
      categorySlug: "tools",
      stock: 200,
      image: IMG.bread,
      description: "فیبر نقطه‌ای برای مونتاژ دائمی مدار.",
      specs: { ابعاد: "7×9 cm" },
    },
    {
      slug: "helping-hands",
      title: "پایه کمکی لحیم‌کاری ذره‌بین‌دار",
      price: 165000,
      brand: "Facksten Tools",
      sku: "TOL-HELP-HANDS",
      categorySlug: "tools",
      stock: 45,
      image: IMG.board,
      description: "پایه کمکی با گیره و ذره‌بین برای لحیم‌کاری.",
      specs: { ذره‌بین: "بله" },
    },
    {
      slug: "usb-ttl-ch340",
      title: "مبدل USB به TTL چیپ CH340",
      price: 65000,
      brand: "Generic",
      sku: "CON-USB-TTL-CH340",
      categorySlug: "connectors",
      stock: 120,
      isPopular: true,
      image: IMG.board,
      description: "مبدل سریال برای پروگرام Pro Mini و دیباگ.",
      specs: { چیپ: "CH340", ولتاژ: "3.3/5 V" },
    },
    {
      slug: "dupont-ff-40",
      title: "کابل جامپر مادگی به مادگی ۴۰ رشته ۳۰ سانتی",
      price: 55000,
      brand: "Generic",
      sku: "CON-JMP-FF40",
      categorySlug: "connectors",
      stock: 160,
      image: IMG.bread,
      description: "کابل فلت مادگی-مادگی برای سنسورها.",
      specs: { نوع: "مادگی-مادگی", طول: "30 cm" },
    },
  ];

  const digital: ProductSeed[] = [
    {
      slug: "esp32-controller-source",
      title: "کد منبع کنترلر ESP32 برای خانه هوشمند",
      price: 120000,
      type: "DIGITAL",
      categorySlug: "digital",
      sku: "DIG-ESP32-SRC",
      stock: 9999,
      icon: "integration_instructions",
      fileLabel: "C++ / INO",
      fileSize: "۱.۸ مگابایت",
      image: "/images/products/esp32-wroom-c.jpg",
      description: "پکیج سورس کنترلر ESP32 شامل MQTT و رابط وب.",
      files: [
        { name: "esp32-controller.zip", url: "/downloads/sample-esp32.txt" },
        { name: "README-fa.txt", url: "/downloads/sample-esp32.txt" },
      ],
      specs: { فرمت: "ZIP", تحویل: "دانلود آنی" },
    },
    {
      slug: "arduino-smart-home",
      title: "پروژه کامل خانه هوشمند آردوینو",
      price: 250000,
      type: "DIGITAL",
      categorySlug: "digital",
      sku: "DIG-ARD-SMARTHOME",
      stock: 9999,
      icon: "home_iot_device",
      fileLabel: "ZIP",
      fileSize: "۴.۲ مگابایت",
      badge: "جدید",
      isNew: true,
      image: IMG.lifestyle,
      description: "شامل شماتیک، کد و لیست قطعات.",
      files: [{ name: "smart-home.zip", url: "/downloads/sample-smarthome.txt" }],
      specs: { فرمت: "ZIP" },
    },
    {
      slug: "pcb-line-follower",
      title: "طراحی PCB ربات مسیریاب خطی",
      price: 85000,
      type: "DIGITAL",
      categorySlug: "digital",
      sku: "DIG-PCB-LINE",
      stock: 9999,
      icon: "schema",
      fileLabel: "Altium / Gerber",
      fileSize: "۸.۵ مگابایت",
      image: IMG.board,
      description: "فایل‌های Gerber و BOM ربات مسیریاب.",
      files: [{ name: "pcb-design.zip", url: "/downloads/sample-pcb.txt" }],
      specs: { فرمت: "Gerber" },
    },
    {
      slug: "pid-motor-lab",
      title: "کیت نرم‌افزاری آزمایشگاه کنترل PID موتور",
      price: 175000,
      type: "DIGITAL",
      categorySlug: "digital",
      sku: "DIG-PID-LAB",
      stock: 9999,
      icon: "integration_instructions",
      fileLabel: "MATLAB / Arduino",
      fileSize: "۳.۱ مگابایت",
      badge: "پیشنهادی",
      isFeatured: true,
      image: IMG.led,
      description: "اسکریپت‌های تیونینگ PID و داشبورد سریال.",
      files: [{ name: "pid-lab.zip", url: "/downloads/sample-esp32.txt" }],
      specs: { فرمت: "ZIP" },
    },
    {
      slug: "fpga-vga-starter",
      title: "پروژه استارتر VGA روی FPGA",
      price: 210000,
      type: "DIGITAL",
      categorySlug: "digital",
      sku: "DIG-FPGA-VGA",
      stock: 9999,
      icon: "schema",
      fileLabel: "Verilog",
      fileSize: "۶.۰ مگابایت",
      image: IMG.board,
      description: "کد Verilog تولید سیگنال VGA.",
      files: [{ name: "fpga-vga.zip", url: "/downloads/sample-pcb.txt" }],
      specs: { زبان: "Verilog" },
    },
    {
      slug: "iot-dashboard-ui",
      title: "قالب داشبورد مانیتورینگ IoT (React)",
      price: 340000,
      type: "DIGITAL",
      categorySlug: "digital",
      sku: "DIG-IOT-DASH",
      stock: 9999,
      icon: "folder_zip",
      fileLabel: "React / TS",
      fileSize: "۱۲ مگابایت",
      badge: "جدید",
      isNew: true,
      image: IMG.laptop,
      description: "قالب داشبورد وب با نمودار لحظه‌ای.",
      files: [{ name: "iot-dashboard.zip", url: "/downloads/sample-smarthome.txt" }],
      specs: { استک: "React + TypeScript" },
    },
  ];

  const all = [
    ...resistors,
    ...capacitors,
    ...diodes,
    ...transistors,
    ...ics,
    ...arduino,
    ...espStm,
    ...sbc,
    ...sensors,
    ...power,
    ...connectors,
    ...tools,
    ...extras,
    ...digital,
  ];

  const categoryOverride: Record<string, string> = {
    "hc-sr04": "sensors-motion",
    "mpu6050": "sensors-motion",
    "pir-hc-sr501": "sensors-motion",
    "dht22": "sensors-env",
    "dht11": "sensors-env",
    "mq2-gas": "sensors-env",
    "bmp280": "sensors-env",
    "oled-128x64": "modules-display",
    "lcd-1602": "modules-display",
    "ssd1306-blue": "modules-display",
    "l298n-driver": "modules-actuators",
    "relay-5v-1ch": "modules-actuators",
    "rfid-rc522": "modules-actuators",
    "servo-sg90": "modules-actuators",
    "stepper-28byj": "modules-actuators",
    "mod-lm2596": "power-modules",
    "mod-mt3608": "power-modules",
    "adapter-12v-1a": "adapters",
    "adapter-5v-2a": "adapters",
    "tp4056-module": "batteries",
    "battery-18650": "batteries",
    "bms-1s-10a": "batteries",
    "header-male-40": "headers",
    "header-female-40": "headers",
    "usb-typec-breakout": "headers",
    "dupont-jumper-65": "cables",
    "dupont-ff-40": "cables",
    "terminal-kf301-2p": "terminals",
    "breadboard-830": "prototyping",
    "protoboard-7x9": "prototyping",
    "soldering-iron-60w": "soldering",
    "solder-wire-100g": "soldering",
    "tweezers-esd": "soldering",
    "helping-hands": "soldering",
    "logic-analyzer-8ch": "measurement",
    "multimeter-aneng": "measurement",
    "usb-ttl-ch340": "measurement",
    "esp32-controller-source": "source-code",
    "arduino-smart-home": "source-code",
    "pid-motor-lab": "source-code",
    "pcb-line-follower": "pcb-design",
    "fpga-vga-starter": "pcb-design",
    "iot-dashboard-ui": "ui-templates",
  };

  return all.map((p) =>
    categoryOverride[p.slug] ? { ...p, categorySlug: categoryOverride[p.slug] } : p,
  );
}
