import type { ComponentDef, PinDef } from "./types";

const MIT = "MIT (Adafruit CAD Parts / Facksten Lab)";
const ADAFRUIT = "https://github.com/adafruit/Adafruit_CAD_Parts";

function unoPins(): PinDef[] {
  const left: PinDef[] = [
    { id: "reset", label: "RESET", x: 8, y: 20, direction: "input", signal: "reset" },
    { id: "3v3", label: "3.3V", x: 8, y: 36, direction: "power", signal: "vcc", voltage: 3.3 },
    { id: "5v", label: "5V", x: 8, y: 52, direction: "power", signal: "vcc", voltage: 5 },
    { id: "gnd1", label: "GND", x: 8, y: 68, direction: "gnd", signal: "gnd" },
    { id: "gnd2", label: "GND", x: 8, y: 84, direction: "gnd", signal: "gnd" },
    { id: "vin", label: "VIN", x: 8, y: 100, direction: "power", signal: "vcc", voltage: 9 },
    { id: "a0", label: "A0", x: 8, y: 124, direction: "input", signal: "analog", arduinoPin: 14 },
    { id: "a1", label: "A1", x: 8, y: 140, direction: "input", signal: "analog", arduinoPin: 15 },
    { id: "a2", label: "A2", x: 8, y: 156, direction: "input", signal: "analog", arduinoPin: 16 },
    { id: "a3", label: "A3", x: 8, y: 172, direction: "input", signal: "analog", arduinoPin: 17 },
    { id: "a4", label: "A4/SDA", x: 8, y: 188, direction: "bidirectional", signal: "i2c-sda", arduinoPin: 18 },
    { id: "a5", label: "A5/SCL", x: 8, y: 204, direction: "bidirectional", signal: "i2c-scl", arduinoPin: 19 },
  ];
  const right: PinDef[] = [];
  for (let i = 0; i <= 13; i++) {
    const signal =
      i === 0 ? ("uart-rx" as const) : i === 1 ? ("uart-tx" as const) : i === 13 ? ("digital" as const) : ("digital" as const);
    right.push({
      id: `d${i}`,
      label: i === 13 ? "D13/LED" : `D${i}`,
      x: 200,
      y: 20 + i * 14,
      direction: "bidirectional",
      signal,
      arduinoPin: i,
      description: i === 13 ? "LED داخلی + پایه دیجیتال ۱۳" : undefined,
    });
  }
  return [...left, ...right];
}

function nanoPins(): PinDef[] {
  const pins: PinDef[] = [
    { id: "d13", label: "D13", x: 120, y: 8, direction: "bidirectional", signal: "digital", arduinoPin: 13 },
    { id: "3v3", label: "3V3", x: 120, y: 24, direction: "power", signal: "vcc", voltage: 3.3 },
    { id: "aref", label: "AREF", x: 120, y: 40, direction: "input", signal: "analog" },
    { id: "a0", label: "A0", x: 120, y: 56, direction: "input", signal: "analog", arduinoPin: 14 },
    { id: "a1", label: "A1", x: 120, y: 72, direction: "input", signal: "analog", arduinoPin: 15 },
    { id: "a2", label: "A2", x: 120, y: 88, direction: "input", signal: "analog", arduinoPin: 16 },
    { id: "a3", label: "A3", x: 120, y: 104, direction: "input", signal: "analog", arduinoPin: 17 },
    { id: "a4", label: "A4", x: 120, y: 120, direction: "bidirectional", signal: "i2c-sda", arduinoPin: 18 },
    { id: "a5", label: "A5", x: 120, y: 136, direction: "bidirectional", signal: "i2c-scl", arduinoPin: 19 },
    { id: "a6", label: "A6", x: 120, y: 152, direction: "input", signal: "analog", arduinoPin: 20 },
    { id: "a7", label: "A7", x: 120, y: 168, direction: "input", signal: "analog", arduinoPin: 21 },
    { id: "5v", label: "5V", x: 8, y: 8, direction: "power", signal: "vcc", voltage: 5 },
    { id: "rst", label: "RST", x: 8, y: 24, direction: "input", signal: "reset" },
    { id: "gnd", label: "GND", x: 8, y: 40, direction: "gnd", signal: "gnd" },
    { id: "vin", label: "VIN", x: 8, y: 56, direction: "power", signal: "vcc", voltage: 9 },
  ];
  for (let i = 0; i <= 12; i++) {
    pins.push({
      id: `d${i}`,
      label: `D${i}`,
      x: 8,
      y: 72 + i * 12,
      direction: "bidirectional",
      signal: i === 0 ? "uart-rx" : i === 1 ? "uart-tx" : "digital",
      arduinoPin: i,
    });
  }
  return pins;
}

/** Static seed catalog — productId/price/stock filled by product-adapter */
export const LAB_COMPONENTS_SEED: ComponentDef[] = [
  {
    id: "arduino-uno",
    name: "Arduino Uno R3",
    slug: "arduino-uno",
    productId: null,
    catalogSlug: "arduino-uno-r3",
    category: "board",
    description: "برد آردوینو Uno با ATmega328P — شبیه‌سازی کامل Blink با avr8js",
    thumbnail: "/lab/thumbs/arduino-uno.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "simulated",
    protocols: ["gpio", "i2c", "spi", "uart", "pwm", "analog"],
    pins: unoPins(),
    voltageRange: { min: 5, max: 5 },
    currentLimit: 40,
    properties: { mcu: "ATmega328P", clock: "16MHz" },
    behaviorModel: { kind: "mcu", mcu: "atmega328p", clockHz: 16_000_000 },
    compatibleBoards: ["arduino-uno"],
    stockStatus: "unknown",
    price: null,
    width: 220,
    height: 230,
  },
  {
    id: "arduino-nano",
    name: "Arduino Nano",
    slug: "arduino-nano",
    productId: null,
    catalogSlug: "arduino-nano",
    category: "board",
    description: "برد فشرده Nano — همان هسته ATmega328P، مسیر شبیه‌سازی Uno",
    thumbnail: "/lab/thumbs/arduino-nano.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "simulated",
    protocols: ["gpio", "i2c", "spi", "uart", "pwm", "analog"],
    pins: nanoPins(),
    voltageRange: { min: 5, max: 5 },
    currentLimit: 40,
    properties: { mcu: "ATmega328P", clock: "16MHz" },
    behaviorModel: { kind: "mcu", mcu: "atmega328p", clockHz: 16_000_000 },
    compatibleBoards: ["arduino-nano", "arduino-uno"],
    stockStatus: "unknown",
    price: null,
    width: 140,
    height: 200,
  },
  {
    id: "breadboard",
    name: "بردبورد ۸۳۰ نقطه",
    slug: "breadboard",
    productId: null,
    catalogSlug: "breadboard-830",
    category: "passive",
    description: "بردبورد نیمه‌اندازه برای سیم‌کشی بدون لحیم — اعتبارسنجی اتصالات",
    thumbnail: "/lab/thumbs/breadboard.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["power"],
    pins: [
      { id: "rail-pos", label: "+", x: 10, y: 10, direction: "power", signal: "vcc", voltage: 5 },
      { id: "rail-gnd", label: "−", x: 10, y: 140, direction: "gnd", signal: "gnd" },
    ],
    voltageRange: { min: 0, max: 5 },
    currentLimit: null,
    properties: { points: 830 },
    behaviorModel: { kind: "breadboard", rows: 30, cols: 10 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 280,
    height: 160,
  },
  {
    id: "led-red",
    name: "LED قرمز ۵mm",
    slug: "led-red",
    productId: null,
    catalogSlug: "led-5mm-red-pack",
    category: "led",
    description: "ال‌ای‌دی قرمز — در شبیه‌سازی با پایه ۱۳ یا خروجی دیجیتال روشن می‌شود",
    thumbnail: "/lab/thumbs/led-red.svg",
    modelUrl: "/lab/models/led-placeholder.json",
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "simulated",
    protocols: ["gpio"],
    pins: [
      { id: "anode", label: "آند (+)", x: 24, y: 8, direction: "input", signal: "digital" },
      { id: "cathode", label: "کاتد (−)", x: 24, y: 48, direction: "gnd", signal: "gnd" },
    ],
    voltageRange: { min: 1.8, max: 2.2 },
    currentLimit: 20,
    properties: { color: "red", diameterMm: 5 },
    behaviorModel: { kind: "led", color: "#ef4444", forwardVoltage: 2.0 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 48,
    height: 56,
  },
  {
    id: "led-rgb",
    name: "LED RGB کاتد مشترک",
    slug: "led-rgb",
    productId: null,
    catalogSlug: "led-5mm-rgb",
    category: "led",
    description: "ال‌ای‌دی RGB — در MVP قابل سیم‌کشی؛ شبیه‌سازی رنگی کامل به‌زودی",
    thumbnail: "/lab/thumbs/led-rgb.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["gpio", "pwm"],
    pins: [
      { id: "r", label: "R", x: 10, y: 8, direction: "input", signal: "pwm" },
      { id: "gnd", label: "GND", x: 30, y: 8, direction: "gnd", signal: "gnd" },
      { id: "g", label: "G", x: 50, y: 8, direction: "input", signal: "pwm" },
      { id: "b", label: "B", x: 70, y: 8, direction: "input", signal: "pwm" },
    ],
    voltageRange: { min: 1.8, max: 3.3 },
    currentLimit: 20,
    properties: { common: "cathode" },
    behaviorModel: { kind: "led", color: "#ffffff", forwardVoltage: 2.2 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 80,
    height: 40,
  },
  {
    id: "resistor-220",
    name: "مقاومت ۲۲۰ اهم",
    slug: "resistor-220",
    productId: null,
    catalogSlug: "resistor-220r",
    category: "passive",
    description: "مقاومت سری استاندارد برای LED روی ۵V",
    thumbnail: "/lab/thumbs/resistor.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["power"],
    pins: [
      { id: "a", label: "A", x: 4, y: 16, direction: "bidirectional", signal: "digital" },
      { id: "b", label: "B", x: 76, y: 16, direction: "bidirectional", signal: "digital" },
    ],
    voltageRange: { min: 0, max: 5 },
    currentLimit: null,
    properties: { ohms: 220, tolerance: "5%" },
    behaviorModel: { kind: "resistor", ohms: 220 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 80,
    height: 32,
  },
  {
    id: "resistor-10k",
    name: "مقاومت ۱۰کیلواهم",
    slug: "resistor-10k",
    productId: null,
    catalogSlug: "resistor-10k",
    category: "passive",
    description: "مقاومت پول‌آپ/پول‌داون رایج برای دکمه",
    thumbnail: "/lab/thumbs/resistor.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["power"],
    pins: [
      { id: "a", label: "A", x: 4, y: 16, direction: "bidirectional", signal: "digital" },
      { id: "b", label: "B", x: 76, y: 16, direction: "bidirectional", signal: "digital" },
    ],
    voltageRange: { min: 0, max: 5 },
    currentLimit: null,
    properties: { ohms: 10000 },
    behaviorModel: { kind: "resistor", ohms: 10000 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 80,
    height: 32,
  },
  {
    id: "button",
    name: "پوش‌باتن لحظه‌ای",
    slug: "button",
    productId: null,
    catalogSlug: null,
    category: "input",
    description: "کلید فشاری — در شبیه‌سازی ورودی دیجیتال (حالت wireable تا اتصال کامل به MCU)",
    thumbnail: "/lab/thumbs/button.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "simulated",
    protocols: ["gpio"],
    pins: [
      { id: "a1", label: "1", x: 8, y: 8, direction: "bidirectional", signal: "digital" },
      { id: "a2", label: "2", x: 48, y: 8, direction: "bidirectional", signal: "digital" },
      { id: "b1", label: "3", x: 8, y: 40, direction: "bidirectional", signal: "digital" },
      { id: "b2", label: "4", x: 48, y: 40, direction: "bidirectional", signal: "digital" },
    ],
    voltageRange: { min: 0, max: 5 },
    currentLimit: null,
    properties: { type: "NO" },
    behaviorModel: { kind: "button", normallyOpen: true },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 56,
    height: 48,
  },
  {
    id: "potentiometer",
    name: "پتانسیومتر ۱۰ک",
    slug: "potentiometer",
    productId: null,
    catalogSlug: null,
    category: "input",
    description: "ولوم آنالوگ — قابل سیم‌کشی به A0؛ شبیه‌سازی مقدار در فاز بعد",
    thumbnail: "/lab/thumbs/pot.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["analog", "power"],
    pins: [
      { id: "vcc", label: "VCC", x: 8, y: 8, direction: "power", signal: "vcc", voltage: 5 },
      { id: "wiper", label: "SIG", x: 32, y: 8, direction: "output", signal: "analog" },
      { id: "gnd", label: "GND", x: 56, y: 8, direction: "gnd", signal: "gnd" },
    ],
    voltageRange: { min: 0, max: 5 },
    currentLimit: null,
    properties: { maxOhms: 10000 },
    behaviorModel: { kind: "potentiometer", maxOhms: 10000 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 64,
    height: 48,
  },
  {
    id: "buzzer",
    name: "بازر پسیو",
    slug: "buzzer",
    productId: null,
    catalogSlug: null,
    category: "actuator",
    description: "بازر پسیو — قابل سیم‌کشی؛ تولید صدا در شبیه‌سازی به‌زودی",
    thumbnail: "/lab/thumbs/buzzer.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["gpio", "pwm"],
    pins: [
      { id: "sig", label: "SIG", x: 24, y: 8, direction: "input", signal: "pwm" },
      { id: "gnd", label: "GND", x: 24, y: 40, direction: "gnd", signal: "gnd" },
    ],
    voltageRange: { min: 3, max: 5 },
    currentLimit: 30,
    properties: { passive: true },
    behaviorModel: { kind: "buzzer", passive: true },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 48,
    height: 48,
  },
  {
    id: "servo-sg90",
    name: "سروو SG90",
    slug: "servo-sg90",
    productId: null,
    catalogSlug: "servo-sg90",
    category: "actuator",
    description: "سروموتور میکرو — قالب آماده با کد PWM؛ مدل رفتاری زاویه در worker",
    thumbnail: "/lab/thumbs/servo.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "simulated",
    protocols: ["pwm", "power"],
    pins: [
      { id: "gnd", label: "GND", x: 10, y: 60, direction: "gnd", signal: "gnd" },
      { id: "vcc", label: "VCC", x: 30, y: 60, direction: "power", signal: "vcc", voltage: 5 },
      { id: "sig", label: "SIG", x: 50, y: 60, direction: "input", signal: "pwm" },
    ],
    voltageRange: { min: 4.8, max: 6 },
    currentLimit: 500,
    properties: { model: "SG90" },
    behaviorModel: { kind: "servo", minUs: 500, maxUs: 2500 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 70,
    height: 70,
  },
  {
    id: "dht22",
    name: "DHT22 دما/رطوبت",
    slug: "dht22",
    productId: null,
    catalogSlug: "dht22",
    category: "sensor",
    description: "سنسور DHT22 — سیم‌کشی و قالب سریال؛ داده حسگر شبیه‌سازی‌شده ثابت برچسب‌خورده",
    thumbnail: "/lab/thumbs/dht22.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["onewire", "power"],
    pins: [
      { id: "vcc", label: "VCC", x: 8, y: 8, direction: "power", signal: "vcc", voltage: 5 },
      { id: "data", label: "DATA", x: 28, y: 8, direction: "bidirectional", signal: "digital" },
      { id: "nc", label: "NC", x: 48, y: 8, direction: "nc", signal: "nc" },
      { id: "gnd", label: "GND", x: 68, y: 8, direction: "gnd", signal: "gnd" },
    ],
    voltageRange: { min: 3.3, max: 5.5 },
    currentLimit: 2.5,
    properties: {},
    behaviorModel: { kind: "dht22" },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 80,
    height: 48,
  },
  {
    id: "hc-sr04",
    name: "HC-SR04 التراسونیک",
    slug: "hc-sr04",
    productId: null,
    catalogSlug: "hc-sr04",
    category: "sensor",
    description: "سنسور فاصله — قالب آماده با Trig/Echo؛ شبیه‌سازی فاصله ثابت برچسب‌خورده در سریال",
    thumbnail: "/lab/thumbs/hcsr04.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "wireable",
    protocols: ["gpio", "power"],
    pins: [
      { id: "vcc", label: "VCC", x: 10, y: 50, direction: "power", signal: "vcc", voltage: 5 },
      { id: "trig", label: "TRIG", x: 30, y: 50, direction: "input", signal: "digital" },
      { id: "echo", label: "ECHO", x: 50, y: 50, direction: "output", signal: "digital" },
      { id: "gnd", label: "GND", x: 70, y: 50, direction: "gnd", signal: "gnd" },
    ],
    voltageRange: { min: 5, max: 5 },
    currentLimit: 15,
    properties: {},
    behaviorModel: { kind: "hcsr04" },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 90,
    height: 60,
  },
  {
    id: "pir",
    name: "PIR HC-SR501",
    slug: "pir",
    productId: null,
    catalogSlug: "pir-hc-sr501",
    category: "sensor",
    description: "سنسور حرکت PIR — قابل سیم‌کشی؛ رویداد حرکت تعاملی به‌زودی",
    thumbnail: "/lab/thumbs/pir.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "3d-only",
    protocols: ["gpio", "power"],
    pins: [
      { id: "vcc", label: "VCC", x: 10, y: 50, direction: "power", signal: "vcc", voltage: 5 },
      { id: "out", label: "OUT", x: 30, y: 50, direction: "output", signal: "digital" },
      { id: "gnd", label: "GND", x: 50, y: 50, direction: "gnd", signal: "gnd" },
    ],
    voltageRange: { min: 4.5, max: 20 },
    currentLimit: null,
    properties: {},
    behaviorModel: { kind: "pir" },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 70,
    height: 60,
  },
  {
    id: "lcd-1602",
    name: "LCD 1602",
    slug: "lcd-1602",
    productId: null,
    catalogSlug: "lcd-1602",
    category: "display",
    description: "نمایشگر کاراکتری ۲×۱۶ — مدل سه‌بعدی/سیم‌کشی؛ شبیه‌سازی متن به‌زودی",
    thumbnail: "/lab/thumbs/lcd1602.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "3d-only",
    protocols: ["gpio", "i2c", "power"],
    pins: [
      { id: "vss", label: "VSS", x: 8, y: 70, direction: "gnd", signal: "gnd" },
      { id: "vdd", label: "VDD", x: 24, y: 70, direction: "power", signal: "vcc", voltage: 5 },
      { id: "sda", label: "SDA", x: 40, y: 70, direction: "bidirectional", signal: "i2c-sda" },
      { id: "scl", label: "SCL", x: 56, y: 70, direction: "bidirectional", signal: "i2c-scl" },
    ],
    voltageRange: { min: 5, max: 5 },
    currentLimit: null,
    properties: { cols: 16, rows: 2 },
    behaviorModel: { kind: "lcd1602", cols: 16, rows: 2 },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 160,
    height: 80,
  },
  {
    id: "oled-128x64",
    name: "OLED 128×64 I2C",
    slug: "oled-128x64",
    productId: null,
    catalogSlug: "oled-128x64",
    category: "display",
    description: "نمایشگر OLED — فقط مدل/کاتالوگ در MVP (۳d-only)",
    thumbnail: "/lab/thumbs/oled.svg",
    modelUrl: null,
    sourceUrl: ADAFRUIT,
    license: MIT,
    simulationStatus: "3d-only",
    protocols: ["i2c", "power"],
    pins: [
      { id: "gnd", label: "GND", x: 8, y: 50, direction: "gnd", signal: "gnd" },
      { id: "vcc", label: "VCC", x: 28, y: 50, direction: "power", signal: "vcc", voltage: 3.3 },
      { id: "scl", label: "SCL", x: 48, y: 50, direction: "bidirectional", signal: "i2c-scl" },
      { id: "sda", label: "SDA", x: 68, y: 50, direction: "bidirectional", signal: "i2c-sda" },
    ],
    voltageRange: { min: 3.3, max: 5 },
    currentLimit: null,
    properties: { width: 128, height: 64 },
    behaviorModel: { kind: "oled", width: 128, height: 64, bus: "i2c" },
    compatibleBoards: ["arduino-uno", "arduino-nano"],
    stockStatus: "unknown",
    price: null,
    width: 90,
    height: 60,
  },
];

export function getComponentById(id: string): ComponentDef | undefined {
  return LAB_COMPONENTS_SEED.find((c) => c.id === id);
}

export function getComponentBySlug(slug: string): ComponentDef | undefined {
  return LAB_COMPONENTS_SEED.find((c) => c.slug === slug || c.catalogSlug === slug);
}

export function listComponents(): ComponentDef[] {
  return LAB_COMPONENTS_SEED;
}

export const SIM_STATUS_LABEL: Record<string, string> = {
  simulated: "قابل شبیه‌سازی",
  wireable: "فقط سیم‌کشی",
  "3d-only": "فقط مدل سه‌بعدی",
};
